### ISSUE TITLE
Bug: Reinforced Grapples not showing up in Select System screen

### ISSUE THREAD

**Issue by aritsune** [jarena3/compcon#27]
**Severity:** High (problem that impairs software function, bad or missing game mechanic implementation)
**Issue Description:** Reinforced Grapples doesn't show up in the list of systems when adding one to a config, whether the pilot has the license/SP for it or not
**Reproduction Steps:** Create Pilot > Create Config> Create Loadout > Add System > look for Reinforced Grapples

Not a data entry error, also potentially affects other systems

**Comment by jarena3** [comment]
fixed in https://github.com/jarena3/compcon/commit/43f4c7453f21f9723d9d0f3ce03ccdb3714f7f49
