### ISSUE TITLE
Bug: Config imported through clipboard pilot import references original pilot

### ISSUE THREAD

**Issue by aritsune** [jarena3/compcon#28]
**Severity:** High (problem that impairs software function, bad or missing game mechanic implementation)
**Issue Description:** Config imported through clipboard pilot import references original pilot
**Reproduction Steps:** Create Pilot > Create Config > Export Pilot to Clipboard > Import that same pilot back in > Check pilots.json in userdata. The reimported config's `pilot_id` is the original pilot's `id`, not the imported pilot's, and calculations (e.g. license availability) are based on the original pilot. Additionally, if the original pilot is deleted, the config fails to load

**Comment by aritsune** [comment]
This doesn't happen if a config is imported on its own, only for configs brought along with pilots

**Comment by jarena3** [comment]
Fixed in https://github.com/jarena3/compcon/commit/774617b1827d2d5e2f88a85697bf57fcec81f54e
