### ISSUE TITLE
Bug Report: Unable to attach both a main weapon and an auxiliary weapon to a Main/Aux mount.

### ISSUE THREAD

**Issue by jarena3** [jarena3/compcon#53]
<strong>Submitted At: </strong>4/11/2019 20:18:59
<strong>Platform: </strong>Windows portable/standalone
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Unable to attach both a main weapon and an auxiliary weapon to a Main/Aux mount.
<strong>Reproduction Steps: </strong>Choose a mech with a main/aux mount. attach a main weapon. no ability to attach an auxiliary weapon.

**Comment by aritsune** [comment]
not seeing this on beta, what mech is this/what weapons are you trying to install?

**Comment by jarena3** [comment]
@jarena3 submitter contacted me about this, turns out it was a confusion with the flex mount's weapon slot reading 'Main/Aux'. I'm going to rename it 'Main **or** Aux' to prevent this in the future
