### ISSUE TITLE
Bug Report: Rank 1 Engineering Integrated Weapon Is listed as 1d6 damage in it's description  when the mount view is expanded in the mech hangar.

### ISSUE THREAD

**Issue by jarena3** [jarena3/compcon#62]
<strong>Submitted At: </strong>4/15/2019 16:07:00
<strong>Platform: </strong>Windows installer
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Rank 1 Engineering Integrated Weapon Is listed as 1d6 damage in it's description  when the mount view is expanded in the mech hangar.
<strong>Reproduction Steps: </strong>Add Engineer to a pilot's talents, open a mech in the mech hangar and expand the description of the Integrated Weapon under Mech Equipment.

**Comment by Fireyheart** [comment]
@jarena3 Should bug fixes like this be delayed until typescript merge?

**Comment by jarena3** [comment]
fixed in https://github.com/jarena3/compcon/commit/4445146eb64be0c3da4fb49c4a4c449e7568b043
