### ISSUE TITLE
Bug: License Reset does not replace old license with new

### ISSUE THREAD

**Issue by jarena3** [jarena3/compcon#7]
<strong>Submitted At: </strong>3/18/2019 15:10:37
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>License Reset does not replace old license with new
<strong>Reproduction Steps: </strong>Create Pilot > Level Pilot > Click Edit License > Reset License > Select New License > Click Confirm > Return to Pilot Page

**Comment by jarena3** [comment]
Fixed in: https://github.com/jarena3/compcon/pull/8, pending build

**Comment by aritsune** [comment]
is this still an issue? seems fine on my end

**Comment by jarena3** [comment]
don't think so, I haven't been able to reproduce it and afaik after the license calc fix I don't think cap'n has either. Closing unless I hear otherwise.
